// <auto-generated />
using System;
using ForaMarket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ForaMarket.Migrations
{
    [DbContext(typeof(ForaDBContext))]
    partial class ForaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ForaMarket.Models.Merchandise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Merchandises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2021, 8, 12, 18, 9, 25, 593, DateTimeKind.Local).AddTicks(4165),
                            Name = "Dead bee body",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2021, 8, 12, 18, 9, 25, 595, DateTimeKind.Local).AddTicks(4091),
                            Name = "A living bee body",
                            Price = 0m
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2021, 8, 12, 18, 9, 25, 595, DateTimeKind.Local).AddTicks(4122),
                            Name = "oh shit, another dead bee body",
                            Price = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
